# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env: 
  JOBS: 1
  OPENRESTY_PREFIX: /usr/local/openresty
jobs:
  # This workflow contains a single job called "build"
  CI:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: 'checkout submodules'
        shell: bash
        run: |
          sudo cpanm --notest Test::Nginx > build.log 2>&1 || (cat build.log && exit 1)
          wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
          sudo apt-get -y install software-properties-common
          sudo add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"
          sudo apt-get update
          sudo apt-get install openresty
          openresty -V
          git clone https://github.com/openresty/test-nginx.git test-nginx
      - name: 'Run Tests'
        run: |
          export PATH=$OPENRESTY_PREFIX/nginx/sbin:$PATH
          prove -Itest-nginx/lib -r t
