name: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      JOBS: 1
      OPENRESTY_PREFIX: /usr/local/openresty
    steps:
      - name: 'before'
        run: |
          wget http://xrl.us/cpanm chmod +x cpanm
          sudo apt-get install build-essential
          sudo apt-get install libncurses5-dev
          sudo apt-get install libpcre3 libpcre3-dev
          sudo apt-get install libreadline-dev
          sudo apt-get install libssl-dev
          yum install perl
          sudo apt-get install luarocks
      - uses: actions/checkout@v2
      - name: 'checkout submodules'
        shell: bash
        run: |
          sudo cpanm --notest Test::Nginx > build.log 2>&1 || (cat build.log && exit 1)
          wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
          sudo apt-get -y install software-properties-common
          sudo add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"
          sudo apt-get update
          sudo apt-get install openresty
          openresty -V
          git clone https://github.com/openresty/test-nginx.git test-nginx
      - name: 'Run Tests'
        run: |
          export PATH=$OPENRESTY_PREFIX/nginx/sbin:$PATH
          prove -Itest-nginx/lib -r t
